version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:  # 将服务连接到自定义网络
      - mynetwork
  mysql:
    image: mysql:8.0.33
    volumes:
      - ./src/main/resources/static:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chooeat
    ports:
      - "3307:3306"
    networks:  # 将服务连接到自定义网络
      - mynetwork
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:  # 将服务连接到自定义网络
      - mynetwork
networks:
  mynetwork:  # 定义自定义网络