version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: chooeatreservation-mysql-1
    depends_on:
      mysql:
        condition: service_healthy 
      redis:
        condition: service_healthy
    networks:
      - mynetwork
  mysql:
    image: mysql:8.0.33
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -uroot -p'$MYSQL_ROOT_PASSWORD' ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/main/resources/static:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chooeat
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - mynetwork
networks:
  mynetwork: {}
